/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_MERKLETREESTUBSERVER_H_
#define JSONRPC_CPP_STUB_MERKLETREESTUBSERVER_H_

#include <jsonrpccpp/server.h>

class MerkleTreeStubServer : public jsonrpc::AbstractServer<MerkleTreeStubServer>
{
    public:
        MerkleTreeStubServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<MerkleTreeStubServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("add", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param01",jsonrpc::JSON_STRING, NULL), &MerkleTreeStubServer::addI);
            this->bindAndAddMethod(jsonrpc::Procedure("element", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param01",jsonrpc::JSON_INTEGER, NULL), &MerkleTreeStubServer::elementI);
            this->bindAndAddMethod(jsonrpc::Procedure("generateCommitment", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param01",jsonrpc::JSON_STRING,"param02",jsonrpc::JSON_STRING,"param03",jsonrpc::JSON_STRING,"param04",jsonrpc::JSON_STRING, NULL), &MerkleTreeStubServer::generateCommitmentI);
            this->bindAndAddMethod(jsonrpc::Procedure("hash", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param01",jsonrpc::JSON_STRING,"param02",jsonrpc::JSON_STRING, NULL), &MerkleTreeStubServer::hashI);
            this->bindAndAddMethod(jsonrpc::Procedure("proveInclusion", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_ARRAY, "param01",jsonrpc::JSON_INTEGER,"param02",jsonrpc::JSON_STRING,"param03",jsonrpc::JSON_STRING, NULL), &MerkleTreeStubServer::proveInclusionI);
            this->bindAndAddMethod(jsonrpc::Procedure("reset", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING,  NULL), &MerkleTreeStubServer::resetI);
            this->bindAndAddMethod(jsonrpc::Procedure("root", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING,  NULL), &MerkleTreeStubServer::rootI);
            this->bindAndAddMethod(jsonrpc::Procedure("simulateAddition", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param01",jsonrpc::JSON_STRING, NULL), &MerkleTreeStubServer::simulateAdditionI);
            this->bindAndAddMethod(jsonrpc::Procedure("status", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT,  NULL), &MerkleTreeStubServer::statusI);
        }

        inline virtual void addI(const Json::Value &request, Json::Value &response)
        {
            response = this->add(request[0u].asString());
        }
        inline virtual void elementI(const Json::Value &request, Json::Value &response)
        {
            response = this->element(request[0u].asInt());
        }
        inline virtual void generateCommitmentI(const Json::Value &request, Json::Value &response)
        {
            response = this->generateCommitment(request[0u].asString(), request[1u].asString(), request[2u].asString(), request[3u].asString());
        }
        inline virtual void hashI(const Json::Value &request, Json::Value &response)
        {
            response = this->hash(request[0u].asString(), request[1u].asString());
        }
        inline virtual void proveInclusionI(const Json::Value &request, Json::Value &response)
        {
            response = this->proveInclusion(request[0u].asInt(), request[1u].asString(), request[2u].asString());
        }
        inline virtual void resetI(const Json::Value &/*request*/, Json::Value &response)
        {
            response = this->reset();
        }
        inline virtual void rootI(const Json::Value &/*request*/, Json::Value &response)
        {
            response = this->root();
        }
        inline virtual void simulateAdditionI(const Json::Value &request, Json::Value &response)
        {
            response = this->simulateAddition(request[0u].asString());
        }
        inline virtual void statusI(const Json::Value &/*request*/, Json::Value &response)
        {
            response = this->status();
        }
        virtual Json::Value add(const std::string& param01) = 0;
        virtual std::string element(int param01) = 0;
        virtual std::string generateCommitment(const std::string& param01, const std::string& param02, const std::string& param03, const std::string& param04) = 0;
        virtual std::string hash(const std::string& param01, const std::string& param02) = 0;
        virtual Json::Value proveInclusion(int param01, const std::string& param02, const std::string& param03) = 0;
        virtual std::string reset() = 0;
        virtual std::string root() = 0;
        virtual Json::Value simulateAddition(const std::string& param01) = 0;
        virtual Json::Value status() = 0;
};

#endif //JSONRPC_CPP_STUB_MERKLETREESTUBSERVER_H_
