version: 2
jobs:
  publish_on_tag:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Publish npm packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
            cd js/packages
            for module in eth eth-contracts eth-generate-verifier-contracts fabric in-memory-platform-state in-memory-secret-store server-client util
            do
              cd k0-$module
              npm publish
              cd ..
            done
            cd k0
            npm publish

workflows:
  version: 2
  main:
    jobs:
      - publish_on_tag:
          context: org-global
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
