version: 2

jobs:
  build_and_push_docker:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true
    steps:
     - checkout
     - run:
          name: "Docker login"
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: "Download latest image"
          command: |
            docker pull appliedblockchain/zktrading
      - run:
          name: "Build main image"
          command: |
            cd cpp
            docker build -f docker/zktrading.Dockerfile -t appliedblockchain/zktrading .
      - run:
          name: "Build app images"
          command: |
            cd cpp
            for IMAGE in setup server mtserver convert-vk
            do
              docker build -f docker/$IMAGE.Dockerfile -t appliedblockchain/zktrading-$IMAGE .
            done
      - run:
          name: "Push images"
          command: |
            for IMAGE in zktrading zktrading-setup zktrading-server zktrading-mtserver zktrading-convert-vk
            do
              docker push appliedblockchain/$IMAGE
              docker tag appliedblockchain/$IMAGE appliedblockchain/$IMAGE:$CIRCLE_TAG
              docker push appliedblockchain/$IMAGE:$CIRCLE_TAG
            done

  publish_npm:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Publish npm packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
            cd js/packages
            for module in eth eth-contracts eth-generate-verifier-contracts fabric in-memory-platform-state in-memory-secret-store server-client util
            do
              cd k0-$module
              npm publish
              cd ..
            done
            cd k0
            npm publish

workflows:
  version: 2
  main:
    jobs:
      - build_and_push_docker:
          context: org-global
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - publish_npm:
          context: org-global
          requires:
            - build_and_push_docker
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
