version: 2

jobs:
  build_cpp:
    docker:
      - image: appliedblockchain/snarkapps-base
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Init Git submodules
          command: git submodule update --init --recursive
      - run:
          name: "C++: CMake"
          command: mkdir cpp/build && cd cpp/build && cmake ..
      - run:
          name: "C++: Make"
          command: cd cpp/build && make
      - persist_to_workspace:
          root: .
          paths:
            - cpp/build/src
            - cpp/build/test
  prepare_node:
    docker:
      - image: appliedblockchain/snarkapps-base
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: cd js && npm i
      - persist_to_workspace:
          root: .
          paths:
            - js/node_modules

  run_private_trade_test:
    docker:
      - image: appliedblockchain/snarkapps-base
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
      - image: appliedblockchain/parity-solo
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Make sure npm modules are installed
          command: cd js && npm i
      - run:
          name: Setup
          command: |
            for x in commitment addition transfer withdrawal
            do
            cpp/build/src/setup ${x} 16 /tmp/zktrade_${x}_pk /tmp/zktrade_${x}_vk
            cpp/build/src/convert_vk /tmp/zktrade_${x}_vk /tmp/zktrade_${x}_vk_alt
            done
      - run:
          name: Start server
          command: |
            cpp/build/src/server 16 /tmp/zktrade_commitment_pk \
            /tmp/zktrade_commitment_vk /tmp/zktrade_addition_pk \
            /tmp/zktrade_addition_vk /tmp/zktrade_transfer_pk \
            /tmp/zktrade_transfer_vk /tmp/zktrade_withdrawal_pk \
            /tmp/zktrade_withdrawal_vk
          background: true
      - run:
          name: Run tests
          command: cd js && node_modules/.bin/mocha test/private-trade.js

workflows:
  version: 2
  main:
    jobs:
      - build_cpp:
          context: org-global
      - prepare_node:
          context: org-global
      - run_private_trade_test:
          context: org-global
          requires:
            - build_cpp
            - prepare_node
