version: 2
jobs:
  publish_on_tag:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: sudo npm i -g lerna
      - run: lerna init
      - run: lerna publish --yes

workflows:
  version: 2
  main:
    jobs:
      - publish_on_tag:
          context: org-global
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
