version: '3.7'

x-custom:
  mtserver: &mtserver
    image: appliedblockchain/zktrading-mtserver
    command: 4 80

services:
  alphatree:
    << : *mtserver
    container_name: alphatree
    ports:
      - 11410:80
  betatree:
    << : *mtserver
    container_name: betatree
    ports:
      - 12410:80
  gammatree:
    << : *mtserver
    container_name: gammatree
    ports:
      - 13410:80
  banktree:
    << : *mtserver
    container_name: banktree
    ports:
      - 14410:80
