version: '3.7'

x-custom:
  server: &server
    image: appliedblockchain/zktrading-server
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 7 /tmp/k0keys/commitment_pk /tmp/k0keys/commitment_vk /tmp/k0keys/addition_pk /tmp/k0keys/addition_vk /tmp/k0keys/transfer_pk /tmp/k0keys/transfer_vk /tmp/k0keys/withdrawal_pk /tmp/k0keys/withdrawal_vk /tmp/k0keys/example_pk /tmp/k0keys/example_vk 80

  mtserver: &mtserver
    image: appliedblockchain/zktrading-mtserver
    command: 7 80

services:
  alphaprover:
    << : *server
    container_name: alphaprover
    ports:
      - 11400:80

  alphatree:
    << : *mtserver
    container_name: alphatree
    ports:
      - 11410:80

  betaprover:
    << : *server
    container_name: betaprover
    ports:
      - 12400:80

  betatree:
    << : *mtserver
    container_name: betatree
    ports:
      - 12410:80

  gammaprover:
    << : *server
    container_name: gammaprover
    ports:
      - 13400:80

  gammatree:
    << : *mtserver
    container_name: gammatree
    ports:
      - 13410:80

  bankprover:
    << : *server
    container_name: bankprover
    ports:
      - 14400:80

  banktree:
    << : *mtserver
    container_name: banktree
    ports:
      - 14410:80
