version: '3.7'

x-custom:
  peer: &peer
    image: hyperledger/fabric-peer:1.2.0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --logging-level=debug

  couchdb: &couch
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=foo

services:

  orderer.orderer.org:
    container_name: orderer.orderer.org
    image: hyperledger/fabric-orderer:1.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/orderer_genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrgMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./artefacts/orderer_genesis.block:/orderer_genesis.block:ro
      - ./crypto-config/ordererOrganizations/orderer.org/orderers/orderer.orderer.org/msp:/msp:ro
      - ./crypto-config/ordererOrganizations/orderer.org/orderers/orderer.orderer.org/tls:/etc/hyperledger/fabric/tls:ro

  verifier:
    image: appliedblockchain/k0-server
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 /tmp/k0keys/example_pk /tmp/k0keys/commitment_vk /tmp/k0keys/example_pk /tmp/k0keys/addition_vk /tmp/k0keys/example_pk /tmp/k0keys/transfer_vk /tmp/k0keys/example_pk /tmp/k0keys/withdrawal_vk /tmp/k0keys/example_pk /tmp/k0keys/example_vk 80

  peer0.alpha.com:
    << : *peer
    container_name: peer0.alpha.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=foo

      - CORE_PEER_ID=peer0.alpha.com
      - CORE_PEER_LOCALMSPID=AlphaCoMSP
      - CORE_PEER_ADDRESS=peer0.alpha.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=alphacouch:5984
    ports:
      - 11751:7051
      - 11753:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/alpha.com/peers/peer0.alpha.com/msp:/msp:ro
      - ./crypto-config/peerOrganizations/alpha.com/peers/peer0.alpha.com/tls:/etc/hyperledger/fabric/tls:ro
      - ./crypto-config/peerOrganizations/alpha.com/users:/etc/hyperledger/msp/users:ro
    depends_on:
      - orderer.orderer.org
      - alphacouch

  alphacouch:
    << : *couch
    container_name: alphacouch
    ports:
      - 11584:5984

  alphatools:
    container_name: alphatools
    image: hyperledger/fabric-tools:1.2.0
    environment:
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/tls/ca.crt
      - CORE_PEER_ADDRESS=peer0.alpha.com:7051
      - CORE_PEER_LOCALMSPID=AlphaCoMSP
    volumes:
      - ./crypto-config/ordererOrganizations/orderer.org/orderers/orderer.orderer.org/tls/ca.crt:/orderer/ca.crt:ro
      - ./artefacts:/artefacts
      - ./crypto-config/peerOrganizations/alpha.com/peers/peer0.alpha.com/tls/ca.crt:/tls/ca.crt:ro
      - ./crypto-config/peerOrganizations/alpha.com/users/Admin@alpha.com/msp:/msp:ro

  peer0.beta.com:
    << : *peer
    container_name: peer0.beta.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=foo

      - CORE_PEER_ID=peer0.beta.com
      - CORE_PEER_LOCALMSPID=BetaCoMSP
      - CORE_PEER_ADDRESS=peer0.beta.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=betacouch:5984
    ports:
      - 12751:7051
      - 12753:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/beta.com/peers/peer0.beta.com/msp:/msp:ro
        - ./crypto-config/peerOrganizations/beta.com/peers/peer0.beta.com/tls:/etc/hyperledger/fabric/tls:ro
        - ./crypto-config/peerOrganizations/beta.com/users:/etc/hyperledger/msp/users:ro
    depends_on:
      - orderer.orderer.org
      - betacouch

  betacouch:
    << : *couch
    container_name: betacouch
    ports:
      - 12584:5984

  betatools:
    container_name: betatools
    image: hyperledger/fabric-tools:1.2.0
    environment:
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/tls/ca.crt
      - CORE_PEER_ADDRESS=peer0.beta.com:7051
      - CORE_PEER_LOCALMSPID=BetaCoMSP
    volumes:
      - ./crypto-config/ordererOrganizations/orderer.org/orderers/orderer.orderer.org/tls/ca.crt:/orderer/ca.crt:ro
      - ./artefacts:/artefacts
      - ./crypto-config/peerOrganizations/beta.com/peers/peer0.beta.com/tls/ca.crt:/tls/ca.crt:ro
      - ./crypto-config/peerOrganizations/beta.com/users/Admin@beta.com/msp:/msp:ro

  peer0.gamma.com:
    << : *peer
    container_name: peer0.gamma.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=foo

      - CORE_PEER_ID=peer0.gamma.com
      - CORE_PEER_LOCALMSPID=GammaCoMSP
      - CORE_PEER_ADDRESS=peer0.gamma.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=gammacouch:5984
    ports:
      - 13751:7051
      - 13753:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/gamma.com/peers/peer0.gamma.com/msp:/msp:ro
        - ./crypto-config/peerOrganizations/gamma.com/peers/peer0.gamma.com/tls:/etc/hyperledger/fabric/tls:ro
        - ./crypto-config/peerOrganizations/gamma.com/users:/etc/hyperledger/msp/users:ro
    depends_on:
      - orderer.orderer.org
      - gammacouch

  gammacouch:
    << : *couch
    container_name: gammacouch
    ports:
      - 13584:5984

  gammatools:
    container_name: gammatools
    image: hyperledger/fabric-tools:1.2.0
    environment:
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/tls/ca.crt
      - CORE_PEER_ADDRESS=peer0.gamma.com:7051
      - CORE_PEER_LOCALMSPID=GammaCoMSP
    volumes:
      - ./crypto-config/ordererOrganizations/orderer.org/orderers/orderer.orderer.org/tls/ca.crt:/orderer/ca.crt:ro
      - ./artefacts:/artefacts
      - ./crypto-config/peerOrganizations/gamma.com/peers/peer0.gamma.com/tls/ca.crt:/tls/ca.crt:ro
      - ./crypto-config/peerOrganizations/gamma.com/users/Admin@gamma.com/msp:/msp:ro

  peer0.bank.com:
    << : *peer
    container_name: peer0.bank.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=foo

      - CORE_PEER_ID=peer0.bank.com
      - CORE_PEER_LOCALMSPID=BankCoMSP
      - CORE_PEER_ADDRESS=peer0.bank.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=bankcouch:5984
    ports:
      - 14751:7051
      - 14753:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/msp:/msp:ro
        - ./crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/tls:/etc/hyperledger/fabric/tls:ro
        - ./crypto-config/peerOrganizations/bank.com/users:/etc/hyperledger/msp/users:ro
    depends_on:
      - orderer.orderer.org
      - bankcouch

  bankcouch:
    << : *couch
    container_name: bankcouch
    ports:
      - 14584:5984

  banktools:
    container_name: banktools
    image: hyperledger/fabric-tools:1.2.0
    environment:
      - CORE_PEER_MSPCONFIGPATH=/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/tls/ca.crt
      - CORE_PEER_ADDRESS=peer0.bank.com:7051
      - CORE_PEER_LOCALMSPID=BankCoMSP
    volumes:
      - ./crypto-config/ordererOrganizations/orderer.org/orderers/orderer.orderer.org/tls/ca.crt:/orderer/ca.crt:ro
      - ./artefacts:/artefacts
      - ./crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/tls/ca.crt:/tls/ca.crt:ro
      - ./crypto-config/peerOrganizations/bank.com/users/Admin@bank.com/msp:/msp:ro
