version: '3.7'

x-custom:
  server: &server
    image: appliedblockchain/zktrading-server
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 /tmp/k0keys/commitment_pk /tmp/k0keys/commitment_vk /tmp/k0keys/addition_pk /tmp/k0keys/addition_vk /tmp/k0keys/transfer_pk /tmp/k0keys/transfer_vk /tmp/k0keys/withdrawal_pk /tmp/k0keys/withdrawal_vk /tmp/k0keys/example_pk /tmp/k0keys/example_vk 80

  server: &mtserver
    image: appliedblockchain/zktrading-mtserver
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 80

services:
  server1:
    << : *server
    ports:
      - 4000:80
  server2:
    << : *server
    ports:
      - 5000:80
  server3:
    << : *server
    ports:
      - 6000:80

  mtserver1:
    << : *mtserver
    ports:
      - 4100:80
  mtserver2:
    << : *mtserver
    ports:
      - 5100:80
  mtserver3:
    << : *mtserver
    ports:
      - 6100:80

  parity:
    image: appliedblockchain/parity-solo-instant:latest
    restart: on-failure
    ports:
      - 8545:8545
      - 8546:8546
