version: '3.7'

x-custom:
  mtserver: &mtserver
    image: appliedblockchain/zktrading-mtserver:v0.0.27
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 80

services:
  alicemtserver:
    << : *mtserver
    container_name: alicemtserver
    ports:
      - 4100:80
  bobmtserver:
    << : *mtserver
    container_name: bobmtserver
    ports:
      - 5100:80
  carolmtserver:
    << : *mtserver
    container_name: carolmtserver
    ports:
      - 6100:80

  parity:
    container_name: parity
    image: appliedblockchain/parity-solo-instant:latest
    ports:
      - 8545:8545
      - 8546:8546

  server:
    container_name: server
    image: appliedblockchain/zktrading-server:v0.0.27
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 /tmp/k0keys/commitment_pk /tmp/k0keys/commitment_vk /tmp/k0keys/addition_pk /tmp/k0keys/addition_vk /tmp/k0keys/transfer_pk /tmp/k0keys/transfer_vk /tmp/k0keys/withdrawal_pk /tmp/k0keys/withdrawal_vk /tmp/k0keys/example_pk /tmp/k0keys/example_vk 80
    ports:
      - 4000:80

