version: '3.7'

x-custom:
  mtserver: &mtserver
    image: appliedblockchain/zktrading-mtserver
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 80

services:
  alicemtserver:
    << : *mtserver
    container_name: alicemtserver
    ports:
      - 4100:80
  bobmtserver:
    << : *mtserver
    container_name: bobmtserver
    ports:
      - 5100:80
  carolmtserver:
    << : *mtserver
    container_name: carolmtserver
    ports:
      - 6100:80

  parity:
    container_name: parity
    image: appliedblockchain/parity-solo-instant:latest
    ports:
      - 8545:8545
      - 8546:8546
