version: '3.7'

x-custom:
  server: &mtserver
    image: appliedblockchain/zktrading-mtserver
    volumes:
      - /tmp/k0keys:/tmp/k0keys:ro
    command: 4 80

services:
  mtserver1:
    << : *mtserver
    ports:
      - 4100:80
  mtserver2:
    << : *mtserver
    ports:
      - 5100:80
  mtserver3:
    << : *mtserver
    ports:
      - 6100:80

  parity:
    image: appliedblockchain/parity-solo-instant:latest
    restart: on-failure
    ports:
      - 8545:8545
      - 8546:8546
